version: '3'
services:
    # Postgis
    db:
        image: mdillon/postgis
        hostname: db
        environment:
                POSTGRES_USER: "postgres"
                POSTGRES_PASSWORD: "docker"
    # Redis
    redis:
        image: redis:3.2.8
        hostname: redis

    # RabbitMQ
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.9
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"  # we forward this port because it's useful for debugging
            - "15672:15672"  # here, we can access rabbitmq management plugin

    # Django
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile
        hostname: web
        command: ./docker/run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8000:8000"
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - db

    # Celery worker
    worker:
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: ./docker/run_celery.sh
        volumes:
            - .:/code:Z
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - rabbit

    # Celery beat
    beat:
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: ./docker/run_celery_beat.sh
        volumes:
            - .:/code:Z
        links:
            - worker
            - db
            - rabbit
            - redis
        depends_on:
            - worker
            - rabbit
