__author__ = '@nolram'
from django.db import transaction
from Crawler.models import Sites, Categorias, SitesCategorias, LinksRSS


@transaction.set_autocommit(False)
def add_pages():
    dic_sites = {}
    sites = [{"titulo": "Zero Hora", "descricao": "Zero Hora", "link": "http://zh.clicrbs.com.br/rs/"},
            {"titulo": "UOL", "descricao": "UOL", "link": "http://www.uol.com.br/"},
            {"titulo": "Terra", "descricao": "Terra", "link": "http://www.terra.com.br/"},
            {"titulo": "Globo", "descricao": "Globo", "link": "http://www.globo.com/"},
            {"titulo": "Estadão", "descricao": "Estadão", "link": "http://www.estadao.com.br/"},
            {"titulo": "Folha de São Paulo", "descricao": "Folha de São Paulo", "link": "http://www.folha.uol.com.br/"},
            {"titulo": "IG", "descricao": "IG", "link": "http://www.ig.com.br/"},
            {"titulo": "R7", "descricao": "R7", "link": "http://www.r7.com/"},
            {"titulo": "Yahoo! Notícias", "descricao": "Yahoo! Notícias", "link": "https://br.noticias.yahoo.com"},
            {"titulo": "MSN", "descricao": "MSN", "link": "http://www.msn.com/pt-br"},
            {"titulo": "G1", "descricao": "G1", "link": "http://g1.globo.com/"},
            {"titulo": "The New York Times", "descricao": "The New York Times", "link": "http://www.nytimes.com/"},
            {"titulo": "BBC UK", "descricao": "BBC UK", "link": "http://www.bbc.com/"},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},
            {"titulo": "", "descricao": "", "link": ""},

            ]
